POST http://localhost:11434/api/chat
content-type: application/json

{ 
    "model": "llama3.2:3b", 
    "messages": [  
        {"role": "system", "content": "Tu es un assistant Python expert."}, 
        {"role": "user", "content": "Comment lire un fichier CSV ?"}, 
        {"role": "assistant", "content": "Tu peux utiliser le module csv de Python..."}, 
        {"role": "user", "content": "Et si le fichier est tres gros ?"} 
        ]
}